export { useLogin } from '@Sdk/authentication'
export { useLogout } from '@Sdk/authentication'
export { useRegister } from '@Sdk/authentication'
export { useForgotPassword } from '@Sdk/authentication'
export { useActivateAccount } from '@Sdk/authentication'
export { useResendActivation } from '@Sdk/authentication'
export { useResetPassword } from '@Sdk/authentication'
export { useDeclareReferee } from '@Sdk/authentication'
export { me } from '@Sdk/authentication'

export { useCreateTeamJoinRequest } from '@Sdk/teams'
export { useCreateTeamWithCoach } from '@Sdk/teams'

export type { RegisterInput } from '@Sdk/model'
export type { Login } from '@Sdk/model'
