import { randomUUID } from 'node:crypto'
import { beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { TeamRole } from '@prisma/client'
import { authHeaderFor } from '../support/authenticate.js'
import { createTestAgent } from '../support/client.js'
import { resetDatabase } from '../support/database.js'
import { assignUserToTeam, createAdmin, createTeam, createUser } from '../support/fixtures.js'

/**
 * Player schema requires id/userId/teamId. id is auto-generated by Prisma (extra
 * field is ignored). userId is overwritten by ctx.request.params.userId in the handler.
 * teamId is used for coach access check. randomUUID() satisfies the string type.
 */
const playerBody = (userId: string, teamId: string, overrides: Partial<Record<string, unknown>> = {}) => ({
  id: randomUUID(),
  userId,
  teamId,
  ...overrides,
})

describe('player — createPlayer — functional API', () => {
  let agent: Awaited<ReturnType<typeof createTestAgent>>

  beforeAll(async () => {
    agent = await createTestAgent()
  })

  beforeEach(async () => {
    await resetDatabase()
  })

  describe('POST /user/{userId}/player', () => {
    it('admin creates a player for any user', async () => {
      const admin = await createAdmin()
      const user = await createUser()
      const team = await createTeam()

      const res = await agent
        .post(`/user/${user.id}/player`)
        .set(authHeaderFor(admin.id, true))
        .send(playerBody(user.id, team.id))

      expect(res.status).toBe(201)
      expect(res.body).toMatchObject({ userId: user.id, teamId: team.id })
    })

    it('coach of the team creates a player', async () => {
      const coach = await createUser()
      const user = await createUser()
      const team = await createTeam()
      await assignUserToTeam(coach.id, team.id, TeamRole.COACH)

      const res = await agent
        .post(`/user/${user.id}/player`)
        .set(authHeaderFor(coach.id))
        .send(playerBody(user.id, team.id))

      expect(res.status).toBe(201)
    })

    it('returns 403 when caller is not admin or coach of the team', async () => {
      const caller = await createUser()
      const user = await createUser()
      const team = await createTeam()

      const res = await agent
        .post(`/user/${user.id}/player`)
        .set(authHeaderFor(caller.id))
        .send(playerBody(user.id, team.id))

      expect(res.status).toBe(403)
    })

    it('returns 403 when coach belongs to a different team', async () => {
      const coach = await createUser()
      const user = await createUser()
      const team1 = await createTeam()
      const team2 = await createTeam()
      await assignUserToTeam(coach.id, team1.id, TeamRole.COACH)

      const res = await agent
        .post(`/user/${user.id}/player`)
        .set(authHeaderFor(coach.id))
        .send(playerBody(user.id, team2.id))

      expect(res.status).toBe(403)
    })

    it('returns 401 without authentication', async () => {
      const user = await createUser()
      const team = await createTeam()

      const res = await agent.post(`/user/${user.id}/player`).send(playerBody(user.id, team.id))

      expect(res.status).toBe(401)
    })
  })
})