services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v5.0.0-alpha.98-unprivileged
    container_name: "swagger-editor-container"
    ports:
      - "8081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    ports:
      - "8082:8080"
    volumes:
      - ./backend/openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    # volumes:
    # - ./frontend:/app
    environment:
      - NODE_ENV=development
