version: "3"
services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    # volumes:
    # - ./frontend:/app
    environment:
      - NODE_ENV=development
