openapi: "3.0.0"
info:
  version: "1"
  title: ""
  description: ""
paths:
  /me:
    get:
      operationId: me
      tags:
        - Authentication
      responses:
        "200":
          description: Current user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithoutPassword"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /login:
    post:
      operationId: login
      tags:
        - Authentication
      security: [] # no auth needed
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Logged in succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenData"
        404:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /logout:
    post:
      operationId: logout
      tags:
        - Authentication
      responses:
        200:
          description: succesful current user's Logout
        500:
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /users:
    get:
      operationId: "getUsers"
      tags:
        - Users
      description: ""
      parameters:
        - in: "query"
          name: "count"
          schema:
            type: "integer"
        - in: "query"
          name: "page"
          schema:
            type: "integer"
      responses:
        200:
          description: "Get list of users"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
  /user:
    post:
      operationId: "createUser"
      description: ""
      tags:
        - Users
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        500:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /user/{userId}/player:
    post:
      operationId: createPlayer
      description: Create a player from user
      tags:
        - Team
      parameters:
        - in: "path"
          name: "userId"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Player"
      responses:
        200:
          description: "successful"
          content:
            application/json: 
              schema: 
                type: string
        404:
          description: "User or team does not exist"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
                
  /teams:
    get:
      operationId: "getTeams"
      description: "get list of teams"
      tags:
        - Teams
      parameters: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Team"
  /team:
    post:
      operationId: "createTeam"
      description: "create a team"
      tags:
        - Team
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
  /team/{id}:
    delete:
      operationId: "removeTeam"
      description: ""
      tags:
        - Team
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
    get:
      operationId: "getTeam"
      description: "get a team info"
      tags:
        - Team
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
        404:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
    patch:
      operationId: "updateTeam"
      description: "Update a team"
      tags:
        - Team
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"

  /team/{teamId}/players:
    get:
      operationId: getTeamPlayers
      description: "Get list of player"
      tags:
        - Teams
      parameters: 
        - in: "path"
          name: "teamId"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "count"
          schema:
            type: "integer"
        - in: "query"
          name: "page"
          schema:
            type: "integer"
      responses:
        200:
          description: "list of player about current team"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Player"
        404:
          description: "not found team"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /team/{teamId}/player/{userId}:
    post:
      operationId: putUserToTeam
      description: "Set a player to the team"
      tags:
        - Teams
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        404:
          description: "team or user are not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
        200:
          description: Successful
          content:
            application/json:
              schema:
                type: boolean
  /user/{id}:
    delete:
      operationId: "removeUser"
      description: ""
      tags:
        - Users
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"

      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "boolean"
        404:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
    patch:
      operationId: "updateUser"
      description: ""
      tags:
        - Users
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        404:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /users/{id}:
    get:
      operationId: "getUser"
      description: ""
      tags:
        - Users
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        403:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
        404:
          description: "Not found user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /areas:
    get:
      operationId: "getAreaList"
      description: "get list of areas"
      tags:
        - Area
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Area"
    post:
      description: "create an area"
      operationId: createArea
      tags:
        - Area
      responses:
        200:
          description: "successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Area"
        500:
          description: "Error during creation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /areas/{id}:  
    delete:
      description: "delete an area"
      operationId: deleteArea
      tags:
        - Area
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /team/{teamId}/games:
    get:
      description: "get list of match about current team"
      operationId: getTeamGames
      tags:
        - Games
        - Team
      parameters:
        - in: "path"
          name: "teamId"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"
        404:
          description: "Team not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /game:
    post:
      description: "Create a game"
      operationId: createMatch
      tags:
        - Games
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Game"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"
        500:
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
  /game/{id}:
    patch:
      description: "Create a game"
      operationId: updateMatch
      tags:
        - Games
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Game"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"
        404:
          description: "Not found game"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"  
        500:
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"
    delete:
      description: "Delete a game"
      operationId: removeGame
      tags:
        - Games
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
        404:
          description: "Not found game"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"  
        500:
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorOutput"

security:
  - jwtAuth: []
components:
  securitySchemes:
    jwtAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
  schemas:
    Area:
      properties:
        name:
          type: string
          nullable: false
        address:
          type: string
          nullable: false
        city:
          type: string
          nullable: false
        longitude:
          type: number
          nullable: false
        latitude:
          type: number
          nullable: false
    Login:
      properties:
        email:
          nullable: false
          type: string
        password:
          nullable: false
          type: string
    User:
      properties:
        lastname:
          nullable: false
          type: "string"
        firstname:
          nullable: false
          type: "string"
        email:
          nullable: false
          type: "string"
        id:
          nullable: false
          type: "string"
        role:
          nullable: true
          type: array
          items:
            type: "string"
        createdAt:
          nullable: false
          type: "number"
        password:
          nullable: false
          type: "string"
    UserWithoutPassword:
      properties:
        lastname:
          nullable: false
          type: "string"
        firstname:
          nullable: false
          type: "string"
        email:
          nullable: false
          type: "string"
        id:
          nullable: false
          type: "string"
        role:
          nullable: true
          type: "array"
          items:
            type: "string"
        createdAt:
          nullable: false
          type: "number"
    TokenData:
      type: object
      properties:
        userId:
          type: string
          nullable: false
        email:
          type: string
          # format: email
          nullable: false
          example: 
            - john@example.com
        token:
          type: string
          nullable: false
    Team:
      properties:
        id:
          nullable: false
          type: "string"
        name:
          nullable: false
          type: "string"
        color:
          nullable: true
          type: "string"
    Player:
      properties:
        id:
          type: string
          nullable: false  
        userId:
          type: string
        jersey:
          type: string
        position:
          type: string
        teamId: 
          type: string
    Game:
      properties:
        id:
          type: string
          nullable: true
        team1:
          type: string
          nullable: false
        score1:
          type: number
          nullable: true
        team2:
          type: string
          nullable: false
        score2:
          type: number
          nullable: true
        date:
          type: integer
          nullable: true
        area:
          $ref: "#/components/schemas/Area"

    ErrorOutput:
      properties:
        status:
          nullable: false
          type: "number"
        message:
          nullable: false
          type: "string"
