export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ForgottenPasswordPage } from './ForgottenPasswordPage'
export { ActivatePage } from './ActivatePage'
export { ResetPasswordPage } from './ResetPasswordPage'
export { MyProfile } from './MyProfile'
