export { AdminUsersPage } from './pages/AdminUsersPage'
export { AdminChampionshipsPage } from './pages/AdminChampionshipsPage'
export { AdminTeamsPage } from './pages/AdminTeamsPage'
export { AdminTeamDeletePage } from './pages/AdminTeamDeletePage'
export { AdminAgeCategoriesPage } from './pages/AdminAgeCategoriesPage'
